# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:

permissions:
  contents: read

jobs:
  test-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==25.1.0
      - name: Lint with black
        run: |
          black --check --diff src/

  test-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort==6.0.0
      - name: Lint with isort
        run: |
          isort --check-only --diff --profile black src/

  test-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.1.1 flake8-bugbear==24.12.12 flake8-pie==0.16.0
      - name: Lint with flake8
        run: |
          flake8 src/

  test-mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with mypy
      run: |
        mypy src/

  test-pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest test/
